"""credentials from env

Revision ID: 7f5c0ec2f8e9
Revises: 12f5800b7e9d
Create Date: 2026-09-28 17:33:26.525295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db  # noqa: F401  自定义列类型 UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "7f5c0ec2f8e9"
down_revision: str | Sequence[str] | None = "12f5800b7e9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # API Key 改为写在 .env 里（D82），不再存数据库
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_providers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_providers",
        sa.Column("provider", sa.VARCHAR(length=32), nullable=False),
        sa.Column("credentials_encrypted", sa.VARCHAR(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    # ### end Alembic commands ###
