"""ai settings

Revision ID: 12f5800b7e9d
Revises: a9e0485024bc
Create Date: 2026-09-28 17:17:53.915134

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db  # noqa: F401  自定义列类型 UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "12f5800b7e9d"
down_revision: str | Sequence[str] | None = "a9e0485024bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_capabilities",
        sa.Column("capability", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("capability"),
    )
    op.create_table(
        "ai_capability_configs",
        sa.Column("capability", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("capability", "provider"),
    )
    op.create_table(
        "ai_providers",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("credentials_encrypted", sa.String(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_providers")
    op.drop_table("ai_capability_configs")
    op.drop_table("ai_capabilities")
    # ### end Alembic commands ###
