"""add characters ai_units and book ai fields

Revision ID: 124af3260e26
Revises: 7f5c0ec2f8e9
Create Date: 2026-09-28 19:12:59.460206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db  # noqa: F401  自定义列类型 UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "124af3260e26"
down_revision: str | Sequence[str] | None = "7f5c0ec2f8e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_units",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("first_page_index", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("lines", sa.JSON(), nullable=False),
        sa.Column("motion_prompt", sa.String(), nullable=True),
        sa.Column("audio_status", sa.String(length=16), nullable=False),
        sa.Column("video_status", sa.String(length=16), nullable=False),
        sa.Column("audio_error", sa.String(), nullable=True),
        sa.Column("video_error", sa.String(), nullable=True),
        sa.Column("audio_source_hash", sa.String(), nullable=True),
        sa.Column("video_source_hash", sa.String(), nullable=True),
        sa.Column("audio_duration_ms", sa.Integer(), nullable=True),
        sa.Column("video_duration_s", sa.Integer(), nullable=True),
        sa.Column("video_resolution", sa.String(), nullable=True),
        sa.Column("audio_version", sa.Integer(), nullable=False),
        sa.Column("video_version", sa.Integer(), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "first_page_index"),
    )
    with op.batch_alter_table("ai_units", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_units_book_id"), ["book_id"], unique=False)

    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_narrator", sa.Boolean(), nullable=False),
        sa.Column("voice_prompt", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_characters_book_id"), ["book_id"], unique=False)

    op.create_table(
        "character_voices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("tts_model", sa.String(), nullable=False),
        sa.Column("voice_id", sa.String(), nullable=False),
        sa.Column("voice_prompt_used", sa.String(), nullable=True),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "provider", "tts_model"),
    )
    with op.batch_alter_table("character_voices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_character_voices_character_id"), ["character_id"], unique=False
        )

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("story", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("read_order", sa.String(length=16), nullable=False, server_default="left_first")
        )
        batch_op.add_column(sa.Column("voice_ready_at", app.db.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("dance_ready_at", app.db.UTCDateTime(), nullable=True))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unit_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("character_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("remote_task_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("next_poll_at", app.db.UTCDateTime(), nullable=True))
        batch_op.create_index(batch_op.f("ix_jobs_character_id"), ["character_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_next_poll_at"), ["next_poll_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_unit_id"), ["unit_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_jobs_character_id", "characters", ["character_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_jobs_unit_id", "ai_units", ["unit_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobs_unit_id", type_="foreignkey")
        batch_op.drop_constraint("fk_jobs_character_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_jobs_unit_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_next_poll_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_character_id"))
        batch_op.drop_column("next_poll_at")
        batch_op.drop_column("remote_task_id")
        batch_op.drop_column("character_id")
        batch_op.drop_column("unit_id")

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_column("dance_ready_at")
        batch_op.drop_column("voice_ready_at")
        batch_op.drop_column("read_order")
        batch_op.drop_column("story")

    with op.batch_alter_table("character_voices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_character_voices_character_id"))

    op.drop_table("character_voices")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_book_id"))

    op.drop_table("characters")
    with op.batch_alter_table("ai_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_units_book_id"))

    op.drop_table("ai_units")
    # ### end Alembic commands ###
